spring.datasource.url=jdbc:postgresql://dpg-da8iesvqj5pc73ejjvg0-a:5432/ats_system_or1s
spring.datasource.username=resume_ats_user
spring.datasource.password=LPdA2Je4Xg3t7kyirAHQjxcpBP4PuBgi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:5432}

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# =========================================================
# GEMINI AI
# =========================================================

gemini.api.key=AQ.Ab8RN6IcH4OzrGASSEI5AphNnJQUOxqrwwHSllIRt2I2zHCdUA
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-3.7-flash:generateContent}